In [10]:
import numpy as np
import pandas as pd

### How to create an numpy array?
#### We can create numpy arrays from native python tuples or lists

In [12]:
t=(1,2,3)
a=np.array(t,dtype= 'int')
a

array([1, 2, 3])

In [13]:
list1 = [1,2,3]
a = np.array(list1,dtype='int')
a

array([1, 2, 3])

In [11]:
a.dtype

dtype('int32')

In [12]:
a = np.array(list1,dtype= 'float32')
a

array([1., 2., 3.], dtype=float32)

In [15]:
list2 = [4.2,5.1,6.3]
b = np.array([list1,list2])
b

array([[1. , 2. , 3. ],
       [4.2, 5.1, 6.3]])

In [16]:
b.dtype

dtype('float64')

In [18]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [19]:
c.shape

(2, 2)

#### Create Special Arrays

In [8]:
np.zeros([2,2])

array([[ 0.,  0.],
       [ 0.,  0.]])

In [9]:
np.ones([2,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
np.empty([2,3]) 

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [22]:
np.linspace(0,10,4) # 3 numbers from 0 to 10

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])