In [1]:
import numpy as np

## Arithmetic Operators

In [2]:
a = np.array( [[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
a * a

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [4]:
a ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

In [5]:
a + a

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [6]:
1/a

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

## Matrix Calculation

In [7]:
A = np.array( [[1,3],[0,1]] )
B = np.array( [[2,2],[3,4]] )

In [8]:
A*B # elementwise product

array([[2, 6],
       [0, 4]])

In [11]:
A.dot(B)  # matrix product

array([[11, 14],
       [ 3,  4]])

In [10]:
np.dot(A, B)

array([[11, 14],
       [ 3,  4]])

In [12]:
np.add(A, B)

array([[3, 5],
       [3, 5]])

## Several Useful Operations

In [17]:
a = np.random.random([2,4]) #Return random floats in the half-open interval [0.0, 1.0).
a

array([[ 0.32019205,  0.31567622,  0.20294444,  0.3071616 ],
       [ 0.39472691,  0.69723294,  0.50040657,  0.53750473]])

In [18]:
a.sum()

3.275845451767001

In [19]:
a.min()

0.20294443643877091

In [20]:
a.max()

0.69723294312625506

In [21]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
b.sum(axis=0) # sum of each column

array([60, 66, 72, 78])

In [19]:
b.sum(axis=1) # sum of each row

array([ 6, 22, 38, 54, 70, 86])

In [20]:
b.min(axis=1) # min of each row

array([ 0,  4,  8, 12, 16, 20])

In [21]:
b.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54],
       [16, 33, 51, 70],
       [20, 41, 63, 86]], dtype=int32)

In [ ]:
#Fibonacci number