## One-dimensional arrays.

In [1]:
import numpy as np

In [2]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [3]:
a[5]

25

In [4]:
a[2:6]

array([ 4,  9, 16, 25], dtype=int32)

In [5]:
a[0:3] = 100
a

array([100, 100, 100,   9,  16,  25,  36,  49,  64,  81], dtype=int32)

In [6]:
a_slice = a[0:5]
a_slice

array([100, 100, 100,   9,  16], dtype=int32)

In [7]:
# change your slice array will affect original array
a_slice[0] = 200

In [8]:
a_slice

array([200, 100, 100,   9,  16], dtype=int32)

In [9]:
a

array([200, 100, 100,   9,  16,  25,  36,  49,  64,  81], dtype=int32)

In [9]:
#fancy indexing
#a = np.arange(10)
#a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#c1 = a[[1,3]]
#c1

array([1, 3])

In [11]:
#c2 = a[[3,1,1]]
#c2

array([3, 1, 1])

In [10]:
# if you want to avoid this, you should use copy method to make a complete copy first
a_slice_2 = a[0:5].copy()
a_slice_2

array([200, 100, 100,   9,  16], dtype=int32)

In [12]:
a_slice_2[0] = 500
a_slice_2

array([500, 100, 100,   9,  16], dtype=int32)

In [13]:
a

array([200, 100, 100,   9,  16,  25,  36,  49,  64,  81], dtype=int32)

## Multidimensional arrays.

In [14]:
def f(x,y):
    return 4*x+y




b = np.fromfunction(f,(3,2),dtype=int)
b

# derive from locations of the matrix
#[[00],[01],[10],[11],[20],[21]]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [15]:
b[0]

array([0, 1])

In [16]:
b[1][0]

4

In [17]:
b[1,0]

4

In [18]:
b[:, 1]

array([1, 5, 9])

In [19]:
c = np.zeros ([5,5])
c

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
column_length = c.shape[1]
column_length

5

In [24]:
for i in range(column_length):
    print(c[i])
    c[i] = i

[ 0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.]


In [25]:
c

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])