In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[3,4,5]],dtype='float')
a

array([[ 1.,  2.,  3.],
       [ 3.,  4.,  5.]])

In [4]:
a.T

array([[ 1.,  3.],
       [ 2.,  4.],
       [ 3.,  5.]])

In [5]:
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.],
       [ 3.,  5.]])

In [6]:
a.transpose?

In [7]:
np.dot(a.T,a)

array([[ 10.,  14.,  18.],
       [ 14.,  20.,  26.],
       [ 18.,  26.,  34.]])

In [8]:
np.linalg.inv(np.dot(a.T,a))
# This calculates the inverse of a matrix

array([[  2.50199979e+14,  -5.00399959e+14,   2.50199979e+14],
       [ -5.00399959e+14,   1.00079992e+15,  -5.00399959e+14],
       [  2.50199979e+14,  -5.00399959e+14,   2.50199979e+14]])

In [6]:
np.allclose?

In [ ]:
from numpy.linalg import inv

a = np.array([[1., 2.], [3., 4.]])

ainv = inv(a)

# here is to check if np.dot(a, ainv) equals to I matrix
np.allclose(np.dot(a, ainv), np.eye(2))

np.allclose(np.dot(ainv, a), np.eye(2))


In [9]:
# return eigenvalues and normalized eigenvectors
np.linalg.eig(np.dot(a.T,a))

(array([  6.36227766e+01,   3.77223398e-01,  -3.19802545e-15]),
 array([[-0.39133557, -0.8247362 ,  0.40824829],
        [-0.5605708 , -0.13817999, -0.81649658],
        [-0.72980603,  0.54837623,  0.40824829]]))

In [15]:
a = np.array([[1., 2.], [3., 4.]])

In [7]:
np.trace?

In [16]:
np.trace(a)

5.0

In [18]:
a3d = np.arange(50).reshape([5,5,2])
a3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [10]:
a3d.transpose([0,2,1])  # .reshape([5,2,5])

array([[[ 0,  2,  4,  6,  8],
        [ 1,  3,  5,  7,  9]],

       [[10, 12, 14, 16, 18],
        [11, 13, 15, 17, 19]],

       [[20, 22, 24, 26, 28],
        [21, 23, 25, 27, 29]],

       [[30, 32, 34, 36, 38],
        [31, 33, 35, 37, 39]],

       [[40, 42, 44, 46, 48],
        [41, 43, 45, 47, 49]]])

In [25]:
a.swapaxes(0,1)

array([[ 1.,  3.],
       [ 2.,  4.]])

In [9]:
a

array([[ 1.,  2.,  3.],
       [ 3.,  4.,  5.]])